// Export all domains
export * from './shared';
export * from './auth';
export * from './public';
export * from './client';
export * from './coach';
export * from './admin';
export * from './analytics';
export * from './video';
export * from './scheduling';
export * from './payments';
export * from './ai';
